
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


minio:
  url: ${MINIO_URL}
  get-bucket: ${MINIO_GET_BUCKET}
  post-bucket: ${MINIO_POST_BUCKET}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}